/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package romanow.abc.desktop;

import retrofit2.Call;
import romanow.abc.core.ErrorList;
import romanow.abc.core.entity.baseentityes.JBoolean;

/**
 *
 * @author Admin
 */
public class TNSKPanel extends TNSKBasePanel {

    /**
     * Creates new form TNSKPanel
     */
    public TNSKPanel() {
        initComponents();
    }

    @Override
    public void initPanel(MainBaseFrame main0) {
        super.initPanel(main0);
        testScanState();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScanOnOff = new javax.swing.JButton();
        GorTransImport = new javax.swing.JButton();

        setLayout(null);

        ScanOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/status_gray.png"))); // NOI18N
        ScanOnOff.setBorderPainted(false);
        ScanOnOff.setContentAreaFilled(false);
        ScanOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScanOnOffActionPerformed(evt);
            }
        });
        add(ScanOnOff);
        ScanOnOff.setBounds(10, 60, 40, 40);

        GorTransImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/upload.png"))); // NOI18N
        GorTransImport.setBorderPainted(false);
        GorTransImport.setContentAreaFilled(false);
        GorTransImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GorTransImportActionPerformed(evt);
            }
        });
        add(GorTransImport);
        GorTransImport.setBounds(20, 20, 30, 30);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void refresh() {
        }
    @Override
    public void eventPanel(int code, int par1, long par2, String par3, Object oo) {
        }
    @Override
    public void shutDown() {
        }

    private void testScanState(){
        new APICall<JBoolean>(main){
            @Override
            public Call<JBoolean> apiFun() {
                return main2.service2.getScanState(main2.debugToken, main.loginUser.getAccount().getPassword());
                }
            @Override
            public void onSucess(JBoolean oo) {
                if (oo.value())
                    ScanOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/status_green.png")));
                else
                    ScanOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/status_gray.png")));
                }
            };
        }

    private void ScanOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScanOnOffActionPerformed
        new APICall<ErrorList>(main){
            @Override
            public Call<ErrorList> apiFun() {
                return main2.service2.changeScanState(main2.debugToken, main.loginUser.getAccount().getPassword());
            }
            @Override
            public void onSucess(ErrorList oo) {
                System.out.println(oo.toString());
                testScanState();
            }
        };
    }//GEN-LAST:event_ScanOnOffActionPerformed

    private void GorTransImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GorTransImportActionPerformed
        new OK(200, 200, "Импортировать ДС с NskGorTrans", new I_Button() {
            @Override
            public void onPush() {
                new APICall<ErrorList>(main) {
                    @Override
                    public Call<ErrorList> apiFun() {
                        return ((TNSKClient)main).service2.gorTransImport(main.debugToken, main.loginUser.getAccount().getPassword());
                    }
                    @Override
                    public void onSucess(ErrorList oo) {
                        System.out.println(oo);
                    }
                };
            }
        });
    }//GEN-LAST:event_GorTransImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GorTransImport;
    private javax.swing.JButton ScanOnOff;
    // End of variables declaration//GEN-END:variables
}
