/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package romanow.abc.desktop;

import retrofit2.Call;
import romanow.abc.core.ErrorList;
import romanow.abc.core.constants.Values;

/**
 *
 * @author Admin
 */
public class TNSKPanel extends BasePanel {

    /**
     * Creates new form TNSKPanel
     */
    public TNSKPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GorTransImport = new javax.swing.JButton();

        setLayout(null);

        GorTransImport.setText("Импорт");
        GorTransImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GorTransImportActionPerformed(evt);
            }
        });
        add(GorTransImport);
        GorTransImport.setBounds(22, 19, 74, 22);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void refresh() {
        }
    @Override
    public void eventPanel(int code, int par1, long par2, String par3, Object oo) {
        }
    @Override
    public void shutDown() {
        }

    private void GorTransImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GorTransImportActionPerformed
        new APICall<ErrorList>(main) {
            @Override
            public Call<ErrorList> apiFun() {
                return ((TNSKClient)main).service2.gorTransImport(main.debugToken, main.loginUser.getAccount().getPassword());
                }
            @Override
            public void onSucess(ErrorList oo) {
                System.out.println(oo);
                }
        };
    }//GEN-LAST:event_GorTransImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GorTransImport;

    // End of variables declaration//GEN-END:variables
}
